<h2 class="text-center mb-3">Register</h2>

<section class="row container-fluid m-auto">
    <form method="POST" class="card p-4 col-12 col-md-6 col-lg-4 m-auto">
    <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <input type="text" required class="form-control" id="name" name="name" placeholder="Your name">
    </div>
        <div class="mb-3">
            <label for="InputEmail" class="form-label">Email address</label>
            <input type="email" class="form-control" id="InputEmail" aria-describedby="emailHelp" name="email" placeholder="Your mail">
        </div>
        <div class="mb-3">
            <label for="InputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="InputPassword" name="password" placeholder="Your password">
        </div>
    
        <button type="submit" class="btn btn-success" name="submit">Register</button>
    </form>
</section>