<h2 class="text-center my-3">Register</h2>

<section class="row container-fluid m-auto mb-3">
    <form method="POST" class="card p-4 col-12 col-md-6 col-lg-4 m-auto">
    <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <input type="text" required class="form-control" id="name" name="name" placeholder="Your name">
    </div>
        <div class="mb-3">
            <label for="InputEmail" class="form-label">Email address</label>
            <input type="email" class="form-control" id="InputEmail" aria-describedby="emailHelp" name="email" placeholder="Your mail">
        </div>
        <div class="mb-3">
            <label for="InputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="InputPassword" name="password" placeholder="Your password">
        </div>
        <div class="mb-3">
            <label for="InputPassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="confirmPassword" name="confirm-password" placeholder="Your password">
        </div>
        <div class="g-recaptcha mb-3 mx-auto" data-sitekey="<?= RECAPTCHA_PUBLIC_KEY ?>"></div>
        <button type="submit" class="btn btn-success" name="submit">Register</button>

    <?php foreach($data['errors'] as $e) : ?>
        <p class="text-danger"><?= implode("<br>", $e) ?></p>    
    <?php endforeach; ?>
        


    </form>
</section>

<script src="https://www.google.com/recaptcha/api.js" async defer></script>
