<h1>Edit User</h1>
<form method="POST">
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <input type="text" required class="form-control" id="name" name="name" placeholder="Your name" value="<?= $data['user']['name']?>">

    <label for="email" class="form-label">Email</label>
    <input type="email" required class="form-control" id="email" name="email" placeholder="Your email" value="<?= $data['user']['email']?>">

    <div class="mt-3">
      <label for="roles" class="form-label">Role</label>
      <select name="role" required>
        <option value="member" <?php if(sizeof(json_decode($data['user']['roles'])) == 1) echo "selected" ?>>Member</option>
        <option value="editor" <?php if(sizeof(json_decode($data['user']['roles'])) == 2) echo "selected" ?>>Editor</option>
        <option value="admin" <?php if(sizeof(json_decode($data['user']['roles'])) == 3) echo "selected" ?>>Admin</option>
      </select>
    </div>

    <button class="mt-4 btn btn-primary" type="submit" id="send" name="submit">Send</button>
  </div>
</form>